### PR TITLE
Update app.py

### PR DESCRIPTION
**Pull request by tailorkuldeep**
Internet working message was printing in loop ...  made my terminal look hanged ; )

### CODE REVIEW

**Comment by yashbhutoria** [comment]
It has to keep printing while there is internet access.

**Comment by tailorkuldeep** [comment]
> It has to keep printing while there is internet access.

yes sir ...it has to but not infinite times..


Screenshot from 2019-04-24 12-40-18

Screenshot from 2019-04-24 12-44-30

**Comment by yashbhutoria** [comment]
Can you restructure if-else statements so that it looks cleaner

**Comment by yashbhutoria** [comment]
Also, please use a meaningful title when making a PR. For example: "Fix Infinite Printing"

**Comment by tailorkuldeep** [comment]
> Can you restructure if-else statements so that it looks cleaner

done..

**Pull request merged**
